FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-build python3-pip gcc mysql-client
WORKDIR /opt/traingbot


ENV DJANGO_SETTINGS_MODULE=tradingbot.settings
ENV TZ='Asia/Kolkata'
